### ISSUE TITLE
Download link not valid

### ISSUE THREAD

**Issue by danielkp1234** [valkyrix/Digispark-Reverse-Shell-Win10#1]
download link expired can you upload the file to the repo so that it can be hosted on the repo or i can host it myself :D

**Comment by valkyrix** [comment]
> download link expired can you upload the file to the repo so that it can be hosted on the repo or i can host it myself :D

Sure thing, you can download it from here: https://eternallybored.org/misc/netcat/
ill update the readme :)

**Comment by danielkp1234** [comment]
I mean the 1fischer link to the .PS1 file

**Comment by valkyrix** [comment]
oh sorry. I believe i created it with msfvenom. I no longer have the original, unfortunately.
https://blog.didierstevens.com/2017/08/16/generating-powershell-scripts-with-msfvenom-on-windows/ would be similar i imagine.
